config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  # Registration and Auth
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :events, only: [ :new, :create, :show, :index, :edit, :update ]
  resources :users, only: [ :show, :edit, :update ] do
    member do
      get :edit
      patch :update
    end
  end
  resources :competitions do
    resources :results, only: [ :new, :create, :edit, :update ]
    post "/participate", to: "competitions#participate"
    post "/judge", to: "competitions#judge"
    post "/set_results", to: "competitions#set_results"
    get "/edit", to: "competitions#edit", as: :edit
    patch "/edit", to: "competitions#update"
  end
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :event, inverse_of: :competitions
  has_many :competitions_users
  has_many :users, through: :competitions_users
  has_many :results, dependent: :destroy

  validates :event, presence: true
  validates :name, presence: true
  validates :min_athlete_weight, presence: true, comparison: { greater_than: 0 }
  validates :max_athlete_weight, presence: true, comparison: { greater_than: :min_athlete_weight }
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  def participate
    @competition = Competition.find_by_id(params[:competition_id])

    if current_user.valid_for_competition?(@competition)
      @competition.competitions_users.create(user_id: current_user.id, role: 1)
      redirect_to @competition, notice: "Вы успешно записались на соревнование."
    else
      redirect_to @competition, alert: "Ваш вес не соответствует требованиям соревнования."
    end
  end
  def judge
    @competition = Competition.find_by_id(params[:competition_id])
    @competition.competitions_users.create(user_id: current_user.id, role: 2)
    redirect_to @competition, notice: "Теперь вы являетесь судьей"
  end
  def new
    @competition = Competition.new
  end

  def create
  end

  def edit
    @competition = Competition.find(params[:competition_id])
  end

  def update
    @competition = Competition.find(params[:id])
    if @competition.update(competition_params)
      redirect_to @competition, notice: "Соревнование успешно обновлено."
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def competition_params
    params.require(:competition).permit(:name, :min_athlete_weight, :max_athlete_weight, :starts_at, :ends_at)
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_competition.html.erb
<div>
  <h3><%= competition.name %></h3>
  <%= link_to 'Редактировать соревнование', edit_competition_path(competition), class: 'btn btn-primary' %>
  <div>
    <p>
      <strong>Минимальный вес:</strong>
      <%= competition.min_athlete_weight %>
      <strong>Максимальный вес:</strong>
      <%= competition.max_athlete_weight %>
    </p>
    <p>
      <strong>Начало в:</strong>
      <%= competition.starts_at.strftime("%d %B %Y %H:%M") %>
      <strong>Конец в:</strong>
      <%= competition.ends_at.strftime("%d %B %Y %H:%M") %>
    </p>
  </div>

  <% if flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% elsif flash[:notice] %>
    <div class="judge judge-danger">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if current_user && current_user.athlete? %>
    <%= button_to "Участвовать", competition_participate_path(competition), method: :post %>
  <% end %>
  <% if current_user && current_user.referee? %>
    <%= button_to "Судить", competition_judge_path(@event.id, competition.id), method: :post %>
  <% end %>
</div>

<style>
    .alert-danger, .judge-danger {
        color: red;
        background-color: #f8d7da;
        border: 1px solid #f5c6cb;
        padding: 10px;
        margin-top: 20px;
    }

    .judge-danger {
        color: green;
        background-color: wheat;
    }
</style>

app/views/competitions/_show.html.erb
<div style="background: gray; border: solid 1px black; margin: 5px 0 5px 0">
  <h3><%= competition.name %></h3>
  <div>
    <p>
      <strong>Минимальный вес:</strong>
      <%= competition.min_athlete_weight %>
      <strong>Максимальный вес:</strong>
      <%= competition.max_athlete_weight %>
    </p>
    <p>
      <strong>Начало в:</strong>
      <%= competition.starts_at.strftime("%d %B %Y %H:%M") %>
      <strong>Конец в:</strong>
      <%= competition.ends_at.strftime("%d %B %Y %H:%M") %>
    </p>
  </div>
  <% if defined?(competition) && competition.present? %>
    <h2>Результаты</h2>
    <% if competition.results.any? %>
      <table>
        <thead>
        <tr>
          <th>Атлет</th>
          <th>Оценка</th>
        </tr>
        </thead>
        <tbody>
        <% competition.results.each do |result| %>
          <tr>
            <td><%= result.athlete.first_name %> <%= result.athlete.last_name %></td>
            <td><%= result.score %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Нет результатов</p>
    <% end %>
  <% else %>
    <p>Соревнование не найдено</p>
  <% end %>

  <% if current_user.referee? %>
    <%= link_to "Добавить результат", new_competition_result_path(competition), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/competitions/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Competitions#edit</h1>
</div>
<h1>Редактировать соревнование</h1>
<%= form_with model: @competition do |form| %>
  <div>
    <%= form.label :name, "Название" %>
    <%= form.text_field :name, required: true %>
  </div>
  <div>
    <%= form.label :min_athlete_weight, "Минимальный вес" %>
    <%= form.number_field :min_athlete_weight, required: true %>
  </div>
  <div>
    <%= form.label :max_athlete_weight, "Максимальный вес" %>
    <%= form.number_field :max_athlete_weight, required: true %>
  </div>
  <%= form.submit "Сохранить изменения" %>
<% end %>