config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  # Registration and Auth
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :events, only: [ :new, :create, :show, :index, :edit, :update ]
  resources :users, only: [ :show, :edit, :update ] do
    member do
      get :edit
      patch :update
    end
  end
  resources :competitions do
    resources :results, only: [ :new, :create, :edit, :update ]
    post "/participate", to: "competitions#participate"
    post "/judge", to: "competitions#judge"
    post "/set_results", to: "competitions#set_results"
    get "/edit", to: "competitions#edit", as: :edit
    patch "/edit", to: "competitions#update"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :roles, dependent: :destroy
  has_many :competitions_users
  has_many :competitions, through: :competitions_users
  has_many :results_as_referee, class_name: "User", foreign_key: :referee_id
  has_many :results_as_athlete, class_name: "User", foreign_key: :athlete_id
  has_many :results_as_referee, class_name: "Result", foreign_key: :referee_id
  has_many :results_as_athlete, class_name: "Result", foreign_key: :athlete_id

  validates :email, presence: true, uniqueness: true
  # validates :password_digest, presence: true, uniqueness: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :birthday, presence: true
  has_secure_password

  def age
    return nil if birthday.nil?
    birthday_date = birthday.to_date

    # Получаем текущую дату
    today = Date.today
    # Вычисляем возраст
    age = today.year - birthday_date.year
    age -= 1 if today < birthday_date.change(year: today.year) # Уменьшаем на 1, если день рождения еще не был в этом году
    age
  end
  def competitions_as_athlete
    competitions_users.select { |cu| cu.role == 1 }.map(&:competition).uniq
    # competitions.joins(:competitions_users).where(competitions_users: { role: 1 })
  end
  def competitions_as_referee
    competitions_users.select { |cu| cu.role == 2 }.map(&:competition).uniq
    # competitions.where(id: competitions_users.where(role: 2).pluck(:competition_id))
  end

  def referee?
    roles.find_by_role_name(:referee).present?
  end
  def athlete?
    roles.find_by_role_name(:athlete).present?
  end

  def valid_for_competition?(competition)
    return false if weight.nil?
    weight >= competition.min_athlete_weight && weight <= competition.max_athlete_weight
  end

  def full_name
    [ last_name, first_name, middle_name ].compact.join(" ")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # пока все пользователи и атлеты, и судьи
      @user.roles.create(role_name: :athlete)
      @user.roles.create(role_name: :referee)
      session[:current_user_id] = @user.id
      redirect_to root_path, notice: "Регистрация прошла успешно."
    else
      redirect_to register_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Информация обновлена успешно."
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation, :first_name, :last_name, :middle_name, :birthday, :weight)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Редактировать профиль</h1>



<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="errors">
      <h2>Ошибки при редактировании:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, "Имя" %>
    <%= f.text_field :first_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :last_name, "Фамилия" %>
    <%= f.text_field :last_name, required: true %>
  </div>

  <div class="field">
    <%= f.label :middle_name, "Отчество" %>
    <%= f.text_field :middle_name %>
  </div>

  <div class="field">
    <%= f.label :email, "Электронная почта" %>
    <%= f.email_field :email, required: true %>
  </div>

  <div class="field">
    <%= f.label :birthday, "Дата рождения" %>
    <%= f.date_field :birthday %>
  </div>

  <div class="field">
    <%= f.label :weight, "Вес" %>
    <%= f.number_field :weight, in: 30..500, step: 0.01 %>
  </div>

  <div class="actions">
    <%= f.submit "Обновить информацию" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Регистрация</h1>

<div>
  <%= form_with model: @user, url: register_path  do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "ошибка") %> при регистрации:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email, required: true %>
    </div>

    <div class="field">
      <%= form.label :password, "Пароль" %>
      <%= form.password_field :password, required: true %>
    </div>

    <div>
      <%= form.label :password_confirmation, "Подтверждение пароля" %>
      <%= form.password_field :password_confirmation, required: true %>
    </div>

    <div class="field">
      <%= form.label :last_name, "Фамилия" %>
      <%= form.text_field :last_name, required: true %>
    </div>

    <div class="field">
      <%= form.label :first_name, "Имя" %>
      <%= form.text_field :first_name, required: true %>
    </div>

    <div class="field">
      <%= form.label :middle_name, "Отчество" %>
      <%= form.text_field :middle_name %>
    </div>

    <div class="field">
      <%= form.label :birthday, "Дата рождения" %>
      <%= form.date_field :birthday %>
    </div>

    <div class="actions">
      <%= submit_tag "Зарегистрироваться" %>
    </div>
  <% end %>
  <div>
    <span>
      Есть аккаунт?
      <%= link_to "Войти", login_path %>
    </span>
  </div>
</div>

app/views/users/show.html.erb
<h1>Страница текущего пользователя</h1>

<%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-primary' %>

<div>
  <p>
    <strong>Фамилия:</strong>
    <%= @user.first_name %>

    <strong>Имя:</strong>
    <%= @user.first_name %>

    <% if @user.middle_name.present? %>
      <strong>Отчество:</strong>
      <%= @user.middle_name %>
    <% end %>

    <% if @user.weight.present? %>
      <strong>Вес:</strong>
      <%= @user.weight %>
    <% end %>
  </p>
  <p>
    <% if @user.athlete? %>
      <strong>Участник:</strong>
      <%= render partial: "competitions/show", collection: @user.competitions_as_athlete, as: :competition %>
    <% end %>
  </p>
  <p>
    <% if @user.referee? %>
      <strong>Судья:</strong>
      <%= render partial: "competitions/show", collection: @user.competitions_as_referee, as: :competition %>
    <% end %>
  </p>

  <p>
    <strong>Результаты участника:</strong>
    <% if @user.results_as_athlete.any? %>
    <ul>
      <% @user.results_as_athlete.each do |result| %>
        <li>
          <%= result.competition.name %>: <%= result.score %> (Судья: <%= result.referee.full_name %>)
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Нет результатов.</p>
  <% end %>
  </p>

  <p>
    <strong>Результаты как судьи:</strong>
    <% if @user.results_as_referee.any? %>
    <ul>
      <% @user.results_as_referee.each do |result| %>
        <li>
          <%= result.competition.name %>: <%= result.score %> (Участник: <%= result.athlete.full_name %>)
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Нет выставленных результатов.</p>
  <% end %>
  </p>


  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <%= button_to "Выйти", logout_path, method: :delete %>
</div>